### ISSUE TITLE
[Bug] `rush build` 失败

### ISSUE THREAD

**Issue by darwintree** [ba-archive/blue-archive#148]
### 问题描述

rush build 失败。系统为win11

```
Rush Multi-Project Build Tool 5.100.1 - https://rushjs.io
Node.js version is 18.16.0 (LTS)


Starting "rush build"

Analyzing repo state... DONE (0.10 seconds)

Executing a maximum of 19 simultaneous processes...

==[ ba-rig ]=======================================================[ 1 of 5 ]==
"ba-rig" did not define any work.

==[ ba-story-player ]==============================================[ 2 of 5 ]==
[commonjs--resolver] Failed to resolve entry for package "P:\blue-archive\lib\ba-story-player\". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "P:\blue-archive\lib\ba-story-player\". The package may have incorrect main/module/exports specified in its package.json.      
    at packageEntryFailure (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28708:11)
    at resolvePackageEntry (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28705:5)
    at tryCleanFsResolve (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28366:28)
    at tryFsResolve (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28313:17)
    at Object.resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28169:24)
    at file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25356:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25256:28)
    at async resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:23931:26)
    at async ModuleLoader.resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:24345:15)      
    at async Object.resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:7984:10)
Returned error code: 1
"ba-story-player" failed to build.
"ba-online-toolbox" is blocked by "ba-story-player".
"blue-archive-story-viewer" is blocked by "ba-story-player".

==[ ba-story-editor ]==============================================[ 5 of 5 ]==
"ba-story-editor" completed successfully in 6.60 seconds.



==[ NO OP: 1 operation ]=======================================================

These operations did not define any work:
  ba-rig

==[ SUCCESS: 1 operation ]=====================================================

These operations completed successfully:
  ba-story-editor    6.60 seconds

==[ BLOCKED: 2 operations ]====================================================

These operations were blocked by dependencies that failed:
  ba-online-toolbox
  blue-archive-story-viewer

==[ FAILURE: 1 operation ]=====================================================

--[ FAILURE: ba-story-player ]-------------------------------[ 0.22 seconds ]--

[commonjs--resolver] Failed to resolve entry for package "P:\blue-archive\lib\ba-story-player\". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "P:\blue-archive\lib\ba-story-player\". The package may have incorrect main/module/exports specified in its package.json.      
    at packageEntryFailure (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28708:11)
    at resolvePackageEntry (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28705:5)
    at tryCleanFsResolve (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28366:28)
    at tryFsResolve (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28313:17)
    at Object.resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28169:24)
    at file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25356:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25256:28)
    at async resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:23931:26)
    at async ModuleLoader.resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:24345:15)      
    at async Object.resolveId (file:///P:/blue-archive/common/temp/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5+sass@1.64.1/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:7984:10)


Operations failed.

rush build (6.72 seconds)
```

### 问题位置

系统仓库

### 复现流程

1. clone 项目
2. 在项目目录下运行

```bash
npm install -g @microsoft/rush
rush update # 在 blue-archive 根目录下执行，下同
rush update-autoinstaller --name rush-prettier
rush install
rush build
```

**Comment by Mark9804** [comment]
宝贝 你的 ba-rig @notnotype

**Comment by Mark9804** [comment]
哦我起猛了，不是 rig 的问题，你重新拉一下仓库看看

另外如果你想 build 的话，需要把 `ba-online-toolbox` 仓库排除掉，那里面会需求一个密钥文件

**Comment by darwintree** [comment]
> 哦我起猛了，不是 rig 的问题，你重新拉一下仓库看看
> 
> 另外如果你想 build 的话，需要把 `ba-online-toolbox` 仓库排除掉，那里面会需求一个密钥文件

还是一样的问题，我看仓库没有更新啊

**Comment by Mark9804** [comment]
如果 `rush update` 已经成功，可以在项目目录中运行 `pnpm build`

**Comment by diyigemt** [comment]
可以试试把`lib/ba-story-player`的`package.json`里的这行
```json
"build": "vite build #&& vue-tsc --emitDeclarationOnly",
```
改成这个
```json
"build": "vite build",
```

**Comment by Mark9804** [comment]
dev 已经修复了这个问题，可以尝试一下
