### ISSUE TITLE
[Bug] 必然复现：阿露 live2d 加载错误

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/blue-archive#90]
### 问题描述

```ts
Uncaught Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 1123 + 907 = 2030 > 1024 or Y: 78 + 862 = 940 > 1024
    at Texture2.set (Texture.ts:607:19)
    at new Texture2 (Texture.ts:199:18)
    at iterateParser (TextureAtlas.ts:251:43)
    at TextureAtlas.ts:202:25
    at loaders.ts:169:21
    at Signal2.dispatch (Signal.ts:138:22)
    at Loader.ts:572:44
    at next (AsyncQueue.ts:271:21)
    at e.use (SoundLoader.ts:71:13)
    at Loader.ts:568:20
```

<img width="478" alt="image" src="https://github.com/ba-archive/blue-archive/assets/9006264/82467e84-e345-4407-baac-56a30825b0c0">

### 问题位置

100006

**Comment by Mark9804** [comment]
通过修改spine的方式解决了
